image: node:alpine

stages:
  - test
  - deploy

.testing: &testing
  stage: test
  before_script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

unit test:
  <<: *testing
  script:
    - npm run test -- --color
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week

lint:
  <<: *testing
  script:
    - npm run lint

build:
  stage: deploy
  before_script:
    - npm install
  script:
    - npm run tsc
    - cp LICENSE README.md package*.json dist/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
  except:
    - tags

deploy version:
  stage: deploy
  before_script:
    - echo $NPMRC > ./.npmrc
  script:
    - npm install
    - 'sed -ie "s/\"version\": \"[0-9]\{1,10\}\.[0-9]\{1,10\}\.[0-9]\{1,10\}\(-\(alpha\|beta\)\{1\}\)\{0,1\}\"/\"version\": \"$CI_COMMIT_TAG\"/g" package.json'
    - npm run tsc
    - cp LICENSE README.md package*.json dist/
    - npm publish dist/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  only:
    - tags
